apiVersion: v1
kind: LimitRange
metadata:
  name: example
spec:
  limits:
    - type: Pod
      min:
        cpu: 50m
        memory: 5Mi
      max:
        cpu: 1
        memory: 1Gi
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 10Mi
      default:
        cpu: 200m
        memory: 100Mi
      min:
        cpu: 50m
        memory: 5Mi
      max:
        cpu: 1
        memory: 1Gi
      maxLimitRequestRatio:
        cpu: 4
        memory: 10
    - type: PersistentVolumeClaim
      min:
        storage: 1Gi
      max:
        storage: 10Gi
# ---
# # LimitRange for Pod or Container
# apiVersion: v1
# kind: LimitRange
# metadata:
#   name: LimitRangeName
#   namespace: default
# spec:
#   limits:
#   # 'default' and 'defaultRequest' may not be specified when type is 'Pod'
#   - type: Container
#     default:
#       cpu: 100m
#       memory: 512Mi
#     defaultRequest:
#       cpu: 100m
#       memory: 256Mi
#     max:
#       cpu: 200m
#       memory: 512Mi
#     min:
#       cpu: 100m
#       memory: 256Mi
# ---
# # LimitRange for PersistentVolumeClaim
# apiVersion: v1
# kind: LimitRange
# metadata:
#   name: LimitRangeName
#   namespace: default
# spec:
#   limits:
#   - type: PersistentVolumeClaim
#     default:
#       storage: 2Gi
#     defaultRequest:
#       storage: 2Gi
#     max:
#       storage: 2Gi
#     min:
#       storage: 2Gi
