apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    - port: 3050
      # targetPort: 6379
      targetPort: 5000
      nodePort: 31515
  selector:
    component: web
