apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  # namespace: default
  # labels:
  #   app: database-pvc
spec:
  # storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
#
#
# accessModes
# ReadWriteOnce   → Can be used by a single node
# ReadOnlyMany    → Multiple nodes can read from this
# ReadWriteMany   → Can be read and written to by many nodes
#
