apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  # namespace: default
  # labels:
  #   app: db-pvc
spec:
  # storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
#
#
# accessModes
# ReadWriteOnce   → Can be used by a single node
# ReadOnlyMany    → Multiple nodes can read from this
# ReadWriteMany   → Can be read and written to by many nodes
#
#

########################################
#
# persistentVolumeReclaimPolicy
# Retain    → The PV is not deleted when the PVC is deleted.
#             The PV is not automatically deleted when the PVC is deleted.
#             The PV will have Release status, and the other PVCs can't use it.
# Recycle   → The PV is recycled (emptied) when the PVC is deleted.
#             The PV is not automatically deleted when the PVC is deleted.
#             The PV will have Available status, and the other PVCs can use it.
# Delete    → The PV is automatically deleted when the PVC is deleted.
#
#########################################
