apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi #This is just a placeholder value to make Kubernetes happy because it is needed when creating a PV
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ''
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-073d77123471b2917
